FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY streamlit-app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код Streamlit
COPY streamlit-app/ .

# Порт
EXPOSE 8501

# Команда запуска
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]